spring:
  application:
    name: minio-upload-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minio_upload_demo
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


minio:
  endpoint: http://localhost:9000
  bucketName: minio-upload-demo # 桶名称
  accessKey: hOuCmQPVDYheb8yMqDyx
  accessSecret: BPCb233b3kTWIbx752b125LbleDvG0WxRZ5UgVbL

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zazhi.minio_upload_demo.controller
knife4j:
  enable: true
  setting:
    language: zh_cn